version: '3.0'

services:
  postgresql:
    image: postgres
    restart: always
    container_name: widget-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=widgetdb

  widget-service:
    build : .
    container_name: widget-service
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    links:
      - postgresql